# dev env setting
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
    region.static: ${S3_REGION_STATIC}
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}

weather:
  endpoint: ${WEATHER_END_POINT}
  serviceKey: ${WEATHER_SERVICE_KEY}

after-login:
  default-success: ${AFTER_LOGIN_DEFAULT_SUCCESS_URL}
  default-fail: ${AFTER_LOGIN_DEFAULT_FAIL_URL}
  oauth2-success: ${AFTER_LOGIN_OAUTH2_SUCCESS_URL}
  oauth2-fail: ${AFTER_LOGIN_OAUTH2_FAIL_URL}
server:
  port: 8888

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expire-period: ${JWT_ACCESS_TOKEN_EXPIRE_PERIOD}
  refresh-token-expire-period: ${JWT_REFRESH_TOKEN_EXPIRE_PERIOD}
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.filter: DEBUG
    org.apache.coyote.http11.Http11Processor: DEBUG
    org.apache.tomcat: DEBUG