# dev env setting
spring:
  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}  # 환경 변수로 치환
            client-secret: ${KAKAO_CLIENT_SECRET}  # 환경 변수로 치환
            client-authentication-method: client_secret_post
            redirect-uri: ${KAKAO_REDIRECT_URI}  # 환경 변수로 치환
            authorization-grant-type: authorization_code
            client-name: kakao
            scope:
              - profile_nickname
              - profile_image
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
    region.static: ${S3_REGION_STATIC}
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}

weather:
  endpoint: ${WEATHER_END_POINT}
  serviceKey: ${WEATHER_SERVICE_KEY}

after-login:
  default-success: ${AFTER_LOGIN_DEFAULT_SUCCESS_URL}
  default-fail: ${AFTER_LOGIN_DEFAULT_FAIL_URL}
  oauth2-success: ${AFTER_LOGIN_OAUTH2_SUCCESS_URL}
  oauth2-fail: ${AFTER_LOGIN_OAUTH2_FAIL_URL}

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expire-period: ${JWT_ACCESS_TOKEN_EXPIRE_PERIOD}
  refresh-token-expire-period: ${JWT_REFRESH_TOKEN_EXPIRE_PERIOD}

logging:
  level:
    root: INFO
    com.fasterxml.jackson: DEBUG
    org.springframework.security: DEBUG  # Spring Security 관련 로그를 더 자세히 보기 위해 DEBUG로 변경
    com.idle.weather: DEBUG  # 프로젝트 패키지 로그를 상세히 보기 위해 DEBUG로 설정